doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            user_id: App\Identity\Infrastructure\Persistence\Doctrine\Type\UserIdType
            area_id: App\Area\Infrastructure\Persistence\Doctrine\Type\AreaIdType
            task_id: App\Task\Infrastructure\Persistence\Doctrine\Type\TaskIdType
            inbox_item_id: App\Inbox\Infrastructure\Persistence\Doctrine\Type\InboxItemIdType
            next_action: App\Task\Infrastructure\Persistence\Doctrine\Type\NextActionType
            note_id: App\Note\Infrastructure\Persistence\Doctrine\Type\NoteIdType
            goal_id: App\Goal\Infrastructure\Persistence\Doctrine\Type\GoalIdType
            daily_review_id: App\Review\Infrastructure\Persistence\Doctrine\Type\DailyReviewIdType
            weekly_review_id: App\Review\Infrastructure\Persistence\Doctrine\Type\WeeklyReviewIdType
            monthly_review_id: App\Review\Infrastructure\Persistence\Doctrine\Type\MonthlyReviewIdType


    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Task:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Task/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Task\Domain\Entity'
            Identity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Identity/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Identity\Domain\Entity'
            Area:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Area/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Area\Domain\Entity'
            InboxItem:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Inbox/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Inbox\Domain\Entity'
            Note:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Note/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Note\Domain\Entity'
            Goal:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Goal/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Goal\Domain\Entity'
            Review:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Review/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Review\Domain\Entity'


        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
