security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        identity_provider:
            memory: ~
        app_user_provider:
            id: App\Identity\Infrastructure\Security\SecurityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Identity\Infrastructure\OAuth\GoogleAuthenticator

            entry_point: App\Identity\Infrastructure\Security\AuthenticationEntryPoint

            logout:
                path: identity_logout
                target: identity_login
                # where to redirect after logout
            remember_me:
                always_remember_me: true

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check$, roles: PUBLIC_ACCESS }

        - { path: ^/, roles: ROLE_USER }
